services:
  frete_rapido:
    image: frete_rapido_app
    hostname: frete_rapido
    container_name: frete_rapido
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env.local
    depends_on:
      - postgres

  postgres:
    image: docker.io/postgres:15.4-alpine
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_frete_rapido
    ports:
      - 5432:5432
    volumes:
      - ./pkg/database/schemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s